on:
  # Trigger the workflow on push
  # but only for the main branch
  push:
    branches:
      - main
  # schedule to run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'

jobs:
  my-job:
    name: ProcessWorkflowJob
    runs-on: ubuntu-latest
    steps:
      - run: python3 ../../queryGithub.py
